// src/components/email.tsx
export const Email = () => {
  const email = new String('supPo    Rt @ mrug esh.dev')
    .toLowerCase()
    .replaceAll(' ', '')
    .split('')
    .reverse()
    .join('');
  return (
    <a href="mailto:${email}">
      {' '}
      <span
        style={{
          unicodeBidi: 'bidi-override',
          direction: 'rtl',
          textAlign: 'left'
        }}
      >
        {email}
      </span>
    </a>
  );
};

export default Email;

// src/lib/email.svelte
<script lang="ts">
  const email = new String('supPo    Rt @ mrug esh.dev')
    .toLowerCase()
    .replaceAll(' ', '')
    .split('')
    .reverse()
    .join('');
</script>

<a href="mailto:${email}"> <span class="reversed">{email}</span></a>

<style>
  .reversed {
    unicode-bidi: bidi-override;
    direction: rtl;
    text-align: left;
  }
</style>
