// src/lib/footer.svelte
<script lang="ts">
  export let defaultType = false;
</script>

<footer class:defaultType class:otherType={!defaultType}>
  <div>
    <p>
      © {new Date().getFullYear()} Mrugesh Mohapatra. All rights reserved.
    </p>
    <p class="mt-2">
      <a aria-label="Terms & Conditions" href="/terms"> Terms </a>
      •
      <a aria-label="Privacy Policy" href="/privacy"> Privacy </a>
      •
      <a aria-label="Refunds & Cancellation Policy" href="/refunds">
        Refunds
      </a>
    </p>
  </div>
</footer>

<style lang="postcss">
  .defaultType {
    @apply font-mono text-gray-700 text-sm text-center;
    @apply mx-8 md:mx-auto py-1 mt-2;
  }

  .defaultType a {
    @apply text-gray-700 hover:text-gray-50;
  }

  .otherType {
    @apply mt-4 text-center;
  }
  .otherType a {
    @apply text-gray-500 hover:text-gray-900 no-underline;
  }
</style>

// src/components/footer.tsx
import Link from 'next/link';

export type FooterProps = {
  defaultType?: boolean;
};
export const Footer: React.FC<FooterProps> = (props: FooterProps) => {
  const { defaultType } = props;
  const footerClass = defaultType
    ? 'font-mono text-gray-700 text-sm text-center mx-8 md:mx-auto mt-8'
    : 'mt-8 text-center';
  const anchorClass = defaultType
    ? 'text-gray-700 hover:text-gray-50 rounded-full hover:bg-gray-500 py-1 px-2'
    : 'text-gray-500 hover:text-gray-50 rounded-full hover:bg-gray-500 py-1 px-2 no-underline';
  return (
    <footer className={footerClass}>
      <div>
        <p>
          © 2012-{new Date().getFullYear()} Mrugesh Mohapatra, Co. All rights
          reserved.
        </p>
        <p className="mt-2">
          {!defaultType && (
            <>
              <Link href="/" aria-label="Home" className={anchorClass}>
                Home
              </Link>
              •
            </>
          )}
          <Link
            href="/terms"
            aria-label="Terms & Conditions"
            className={anchorClass}
          >
            Terms
          </Link>
          •
          <Link
            href="/privacy"
            aria-label="Privacy Policy"
            className={anchorClass}
          >
            Privacy
          </Link>
          •
          <Link
            href="/refunds"
            aria-label="Refunds & Cancellation Policy"
            className={anchorClass}
          >
            Refunds
          </Link>
        </p>
      </div>
    </footer>
  );
};
